### ISSUE TITLE
build x2 kotlin with gradle

### ISSUE THREAD

**Issue by dio99** [skoky/mylaps-x2-kotlin#1]
> Task :cinteropMylapsLinuxX64 FAILED
Exception in thread "main" java.lang.Error: /tmp/tmp233201051445804722.c:1:10: fatal error: 'MylapsSDK.h' file not found
        at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:152)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.indexDeclarations(Indexer.kt:1003)
        at org.jetbrains.kotlin.native.interop.indexer.IndexerKt.buildNativeIndexImpl(Indexer.kt:992)
        at org.jetbrains.kotlin.native.interop.indexer.NativeIndexKt.buildNativeIndex(NativeIndex.kt:91)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:230)
        at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:46)
        at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:44)
        at org.jetbrains.kotlin.cli.utilities.MainKt.mainImpl(main.kt:19)
        at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:37)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cinteropMylapsLinuxX64'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

**Comment by skoky** [comment]
yes, you are probably missing SDK from MyLaps. This is covered under MyLaps' NDA. Please contact them to provide you with package containing the MylapsSDK.h.
